name: phi4-deploy-env-v2
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - torch==2.3.1
    - torchvision
    - torchaudio
    - transformers>=4.42.0
    - accelerate>=0.31.0
    - peft>=0.11.0
    - trl>=0.9.0
    - datasets>=2.19.0
    - pandas
    - azureml-sdk