name: pii-finetune-env-final-stable-v2
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch=2.3.1
  - pytorch-cuda=12.1
  - pip:
    - transformers==4.49.0
    - peft==0.14.0
    - trl==0.15.2
    - accelerate==1.5.2
    - datasets==3.4.0
    - sentencepiece==0.2.0
    - azureml-acft-accelerator==0.0.63
    - azureml_acft_common_components==0.0.63
    - azureml-acft-contrib-hf-nlp==0.0.63
    - azureml-evaluate-mlflow==0.0.63
    - azureml-metrics[text]==0.0.63
    - mltable==1.6.1
    - diffusers==0.31.0
    - rouge-score==0.1.2
    - sacrebleu==2.4.3
    - einops==0.8.1
    - aiohttp==3.10.10
    - tiktoken==0.8.0
    - packaging==24.1
    - timm==1.0.11
    - azure-identity
    - bitsandbytes==0.43.1
    - triton==2.3.0